<?php

   include('../../functions.php');

   $login_id = $_SESSION['crm_credentials']['user_id'];

   $table_name = 'tbl_leads';
   $field_name = 'id';    

   if(isset($_POST['search'])){


      if(isset($_POST['name']) && $_POST['name'] != ""){
          $condition = " name LIKE '%".$_POST['name']."%' AND delete_status = '0' ";
      }else if(isset($_POST['mobile_number']) && $_POST['mobile_number'] != ""){
          $condition = " mobile_number LIKE '%".$_POST['mobile_number']."%' AND delete_status = '0' ";
      }

      $leads = "SELECT * FROM ".$table_name." WHERE ".$condition;
      $leads = getRaw($leads);

   }

?>



<!DOCTYPE html>

<html>

   <?php require_once('../../include/headerscript.php'); ?>

   <body class="fixed-left">

      <!-- Begin page -->

      <div id="wrapper">

         <!-- Top Bar Start -->

         <?php require_once('../../include/topbar.php'); ?>

         <!-- Top Bar End -->

         <!-- ========== Left Sidebar Start ========== -->

         <?php require_once('../../include/sidebar.php'); ?>

         <!-- Left Sidebar End -->

         <!-- ============================================================== -->

         <!-- Start Page Content here -->

         <!-- ============================================================== -->

         <div class="content-page">

            <!-- Start content -->

            <div class="content">

               <div class="container">

     <!--               <div class="row">

                     <div class="col-md-6">

                        <div class="page-title-box">

                           <h4 class="page-title">Add Booking</h4>

                           <div class="clearfix"></div>

                        </div>

                     </div>                   

                  </div> -->

              <?php if(isset($success) || isset($warning) || isset($error)){ ?>

              <div class="row">

                <div class="col-md-12 p-t-30">

                    <?php if(isset($success)){ ?>

                       <div class="alert alert-success"><?php echo $success; ?></div>

                    <?php }else if(isset($warning)){ ?>

                       <div class="alert alert-warning"><?php echo $warning; ?></div>

                    <?php }else if(isset($error)){ ?>

                       <div class="alert alert-danger"><?php echo $error; ?></div>

                    <?php } ?>

                 </div>
              </div>
            <?php } ?>
              <hr>
              <div class="row">
                <div class="col-md-12">

                    <!-- <div class="col-md-2"></div> -->
                    <form method="POST">
                      
                      <div class="col-md-3">

                          <div class="form-group">

                             <label for="name">Name</label>

                             <input type="text" name="name" parsley-trigger="change" class="form-control" id="name" value="<?php if(isset($_POST['name'])){ echo $_POST['name']; } ?>" placeholder="Enter Name">

                          </div>

                       </div>

                      
                      <div class="col-md-3">
                        <div class="form-group">
                           <label for="mobile_number">Mobile Number</label>
                           <input type="text" class="form-control" id="mobile_number" name="mobile_number" placeholder="Enter Mobile Number" value="<?php if(isset($_POST['mobile_number'])){ echo $_POST['mobile_number']; } ?>" >

                        </div>  
                      </div>

                      <div class="col-md-4 pt-2">
                        <br>                      
                        <button type="submit" name="search" class="btn btn-primary btb-md"><i class="fa fa-search"></i> Search</button>
                      </div>
                  </form>
                    
                </div>
            </div>

            <hr>

            <div class="row">
              
              <table class="table table-striped table-condensed table-hover table-bordered">
                <thead>
                  <th>#</th>
                  <th>Generated By</th>
                  <th>Code</th>
                  <th>Date</th>
                  <th>Name</th>
                  <th>Mobile Number</th>
                  <th>Phone</th>
                  <th>Email</th>
                  <th>Occupation</th>
                  <th>Company</th>
                  <th>Address</th>
                </thead>

                <tbody>
                  <?php if(isset($leads) && count($leads) > 0){ ?>
                    <?php $i=1; foreach($leads as $rs){ ?>
                        <tr>
                          <td><?php echo $i++; ?></td>
                          <td><?php echo getEmployeeName($rs['employee_id']); ?></td>
                          <td><?php echo $rs['code']; ?></td>
                          <td><?php echo $rs['date']; ?></td>
                          <td><?php echo $rs['name']; ?></td>
                          <td><?php echo $rs['mobile_number']; ?></td>
                          <td><?php echo $rs['phone']; ?></td>
                          <td><?php echo $rs['email']; ?></td>
                          <td><?php echo $rs['occupation']; ?></td>
                          <td><?php echo $rs['company']; ?></td>
                          <td><?php echo $rs['street_address']; ?></td>
                    </tr>
                    <?php } ?>
                    <?php } ?>
                </tbody>
              </table>

            </div>
                 

               </div>

               <!-- container -->

            </div>

            <!-- content -->

         </div>

         <!-- ============================================================== -->

         <!-- End of the page -->

         <!-- ============================================================== -->

      </div>

      <!-- END wrapper -->

      <!-- START Footerscript -->

      <?php require_once('../../include/footerscript.php'); ?>
      <?php require_once('../../include/footer.php'); ?>

   </body>

</html>
